services:
  mainpage:
    build:
      context: .
      dockerfile: apps/mainpage/Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - apps/api/.env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  test-api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "4001:4001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/testdb
      - PORT=4001
      - NODE_ENV=test
    depends_on:
      - mongodb

volumes:
  mongodb_data:

networks:
  default:
    name: my-network